### ISSUE TITLE
Bang ini kok ga bisa pas kuu jalanin python2 call.py

### ISSUE THREAD

**Issue by gatot17** [Aldi098/Call#1]

**Comment by Aldi098** [comment]
?

**Comment by gatot17** [comment]
Kan marah

Pada tanggal Sel, 11 Jan 2022 09.42, XENZI GANZZ ***@***.***>
menulis:

**Comment by Aldi098** [comment]
coba pkg install python2

**Comment by gatot17** [comment]
Udah bang pkg install python2,pkg install python3 pun udah

Pada tanggal Sel, 11 Jan 2022 15.06, XENZI GANZZ ***@***.***>
menulis:

**Comment by gatot17** [comment]
👍👍
